### ISSUE TITLE
not connecting through ssh

### ISSUE THREAD

**Issue by mmrabbani** [alireza0/alireza0.github.io#2]
با سلام
یک پیشنهاد دیگر برای امنیت می‌تواند آن باشد که از طریق SSH و بدون پروکسی یا VPN به سرور متصل نشویم، علی الخصوص وقتی قرار است از پروتکل reality استفاده کنیم و سرور ما خودش را جای سرور یک سرویس مطرح مثل yahoo جا میزند و دیگر در این حالت ssh زدن به سرور yahoo طبیعی نیست.

راه حل جایگزین: استفاده از پروکسی یا VPN، استفاده از پنل اتصال به سرور خود VPS provider، استفاده از سرویس های web SSH که در این مورد آخر باید کاملا به آن سرویس اعتماد داشت

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی شما
خیلی موافق نیستم. با یک آدرس IP میتونه بینهایت سرویس از سایتهای متفاوت سرویس داده بشه.
ولی به نکته خوبی اشاره کردین و برای امنیت ssh حتما باید مطلب بنویسم.

**Comment by mmrabbani** [comment]
ما که دقیقا نمی‌دونیم فیلترچی چطور تصمیم می‌گیره که فیلتر کنه. ولی چند ماه پیش که موجی از فیلترینگ انجام شد، یه موضوعی که مطرح شد، همین موضوع بود.
 من الان نمی‌دونم دقیقا کجاها دیدم. ولی مثلا یه سرچ کوتاه که زدم چنین چیزی رو پیدا کردم.
 https://t.me/iSegaro/57
 البته که اون زمان مطالب بیشتری دیدم.

**Comment by alireza0** [comment]
دقیقا به همین دلیل نباید باعث انتشار مطالبی بشیم که صحتشون رو نمیتونید به راحتی تایید کنیم.
مخصوصا از نظر تکنولوژی استفاده شده.
مطالب امنیتی زیاده، بهتره اونهایی که خیلی به کاربرها توی این زمینه کمک حتمی میکنه رو اضافه کنیم.
سپاسگزارم
